"""Byte-preserving ownership checks for optional generated command files."""
import unittest

import test_runtime as runtime


class PromptOwnershipTests(unittest.TestCase):
    setUp = runtime.RuntimeTests.setUp
    run_cmd = runtime.RuntimeTests.run_cmd
    tree_bytes = runtime.RuntimeTests.tree_bytes

    def fixture(self):
        (self.target / 'AXIARCH.md').write_text('Project Native Language: Japanese\n', encoding='utf-8')
        for lang, title in (('ja', '日本語の作業'), ('en', 'Review task')):
            library = self.target / f'axiarch-prompts/{lang}/develop'
            library.mkdir(parents=True)
            (library / 'demo.md').write_text(f'# {title} \ufffd\n', encoding='utf-8')
            (library / 'good.md').write_text('# Unchanged companion\n', encoding='utf-8')
            protocol = self.target / f'axiarch-rules/{lang}/LOADING_PROTOCOL.md'
            protocol.parent.mkdir(parents=True)
            protocol.write_text('# Loading\n', encoding='utf-8')
        self.command = self.target / '.claude/commands/axiarch-demo.md'

    def prompts(self, lang, *args, expected=0):
        return self.run_cmd(['bash', runtime.SCRIPTS / 'axiarch-prompts-install.sh',
                             '--target', self.target, '--lang', lang, *args], expected=expected)

    def test_corrupted_utf8_is_preserved_in_regeneration_cleanup_and_previews(self):
        self.fixture()
        for lang in ('ja', 'en'):
            self.prompts(lang)
            original = self.command.read_bytes()
            self.assertIn('\ufffd'.encode(), original)
            damaged = original.replace('\ufffd'.encode(), b'\xff', 1)
            self.assertNotEqual(original, damaged)
            self.command.write_bytes(damaged)
            companion = self.target / f'axiarch-prompts/{lang}/develop/good.md'
            companion.write_text('# Pending companion update\n', encoding='utf-8')
            before = self.tree_bytes()
            for options in ((), ('--clean',), ('--dry-run',), ('--clean', '--dry-run')):
                with self.subTest(lang=lang, options=options):
                    result = self.prompts(lang, *options, expected=3)
                    self.assertIn('preserved custom, edited or legacy commands', result.stderr)
                    self.assertNotIn('Traceback', result.stderr)
                    self.assertNotIn('description:', result.stderr)
                    self.assertEqual(self.tree_bytes(), before)
            # Restore only the known generated bytes in this synthetic fixture.
            self.command.write_bytes(original)
            self.prompts(lang)
            self.assertIn(b'Pending companion update',
                          (self.command.parent / 'axiarch-good.md').read_bytes())

    def test_valid_replacement_character_is_not_itself_treated_as_corruption(self):
        self.fixture()
        for lang in ('ja', 'en'):
            self.prompts(lang)
            before = self.tree_bytes()
            self.prompts(lang)
            self.prompts(lang, '--dry-run')
            self.prompts(lang, '--clean', '--dry-run')
            self.assertEqual(self.tree_bytes(), before)
            self.prompts(lang, '--clean')
            self.assertFalse(self.command.exists())

    def test_valid_utf8_edits_are_preserved_before_any_cleanup(self):
        self.fixture()
        for lang in ('ja', 'en'):
            self.prompts(lang)
            original = self.command.read_bytes()
            self.command.write_bytes(original + '\n利用者の変更 / User edit\n'.encode())
            before = self.tree_bytes()
            for options in ((), ('--clean',)):
                self.prompts(lang, *options, expected=3)
                self.assertEqual(self.tree_bytes(), before)
            self.command.write_bytes(original)
