#!/usr/bin/env bash
# =============================================================================
# Axiarch §7.6 ANTI-FULL-OVERWRITE Enforcement (PreToolUse hook)
# https://github.com/hiroyuki-miyauchi/axiarch
#
# Physically blocks Write tool calls that target existing files, directing the
# AI to use Edit (diff-based) instead. This reduces the known §7.6
# ANTI-FULL-OVERWRITE violation pattern that reminder-only enforcement cannot
# reliably stop.
#
# Hook contract (PreToolUse):
#   - stdin: JSON with `tool_name`, `tool_input.file_path`, etc.
#   - stdout: optional JSON output controlling the tool decision
#   - exit code 2 + stderr message: also blocks the tool
#
# Decision logic:
#   1. apply_patch → inspect add/move destinations; focused updates remain allowed
#   2. Tool is not Write/apply_patch → allow (exit 0, no output)
#   3. malformed input or empty/missing Write path → stop (exit 2)
#   4. file_path does not exist on disk → creation, allow
#   5. file_path exists → DENY with §7.6 violation message
#
# Whitelist support (future-friendly):
#   `.claude/axiarch-overwrite-allow.txt` or `.codex/axiarch-overwrite-allow.txt` (one path/glob per line) bypasses the
#   block — useful for autogenerated artefacts. Comments (#) and empty lines
#   are skipped.
#
# Requires Python 3 and the distributed axiarch_hook.py / axiarch_state.py helpers.
# jq is not required. Bash shell.
# =============================================================================

set -uo pipefail

# -----------------------------------------------------------------------------
# Resolve project directory
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-}"
if [[ -z "${PROJECT_DIR}" || ! -d "${PROJECT_DIR}" ]]; then
  SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  PROJECT_DIR="$(dirname "${SCRIPT_DIR}")"
fi

# -----------------------------------------------------------------------------
# Read hook input from stdin
# -----------------------------------------------------------------------------
INPUT=""

# -----------------------------------------------------------------------------
# Extract tool_name and file_path
# Decode actual JSON regardless of jq availability. Never infer paths by regex.
# -----------------------------------------------------------------------------
TOOL_NAME=""
FILE_PATH=""

command -v python3 >/dev/null 2>&1 || {
  printf 'Axiarch Write guard requires Python 3; operation not approved.\n' >&2
  exit 2
}
HOOK_HELPER="$(dirname "${BASH_SOURCE[0]}")/axiarch_hook.py"
INPUT="$(python3 "$HOOK_HELPER" normalize)" || exit 2
PROJECT_DIR="$(python3 -c 'import os, sys; sys.stdout.write(os.path.realpath(sys.argv[1]) + ".")' "$PROJECT_DIR")" || exit 2
PROJECT_DIR="${PROJECT_DIR%.}"
decode_field() {
  printf '%s' "$INPUT" | python3 -c '
import json, os, sys
try:
    data = json.load(sys.stdin)  # Raw input was validated by axiarch_hook.py.
    if not isinstance(data, dict): raise ValueError("object required")
    value = data.get("tool_name") if sys.argv[1] == "tool" else data.get("tool_input", {}).get("file_path")
    if not isinstance(value, str) or not value or "\x00" in value: raise ValueError("nonempty string required")
    if sys.argv[1] != "tool":
        base = data.get("cwd", os.path.abspath(sys.argv[2]))
        if not isinstance(base, str) or not base or "\x00" in base or not os.path.isabs(base) or not os.path.isdir(base):
            raise ValueError("absolute available cwd required")
        # Preserve symlink/.. filesystem semantics for the existence check.
        value = os.path.join(base, value)
        if sys.argv[1] == "canonical": value = os.path.realpath(value)
    # A sentinel preserves trailing newlines through Bash command substitution.
    sys.stdout.write(value + ".")
except (ValueError, TypeError, AttributeError):
    print("Invalid Axiarch hook input; operation not approved.", file=sys.stderr)
    sys.exit(2)
' "$1" "$PROJECT_DIR"
}
TOOL_NAME="$(decode_field tool)" || exit 2
TOOL_NAME="${TOOL_NAME%.}"

if [[ "$TOOL_NAME" == "Write" || "$TOOL_NAME" == "apply_patch" ]]; then
  PROJECT_DIR=$(printf '%s' "$INPUT" | python3 "$HOOK_HELPER" project --project "$PROJECT_DIR") || exit 2
  PROJECT_DIR="${PROJECT_DIR%.}"
fi

if [[ "${TOOL_NAME}" == "apply_patch" ]]; then
  printf '%s' "$INPUT" | python3 "$HOOK_HELPER" protect-patch --project "$PROJECT_DIR"
  exit $?
fi

# -----------------------------------------------------------------------------
# Allow: tool is not Write
# -----------------------------------------------------------------------------
if [[ "${TOOL_NAME}" != "Write" ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# A Write event must have an unambiguous path before deciding permission.
# -----------------------------------------------------------------------------
FILE_PATH="$(decode_field path)" || exit 2
FILE_PATH="${FILE_PATH%.}"

# -----------------------------------------------------------------------------
# Allow: file does not exist (Write = creation, not overwrite)
# -----------------------------------------------------------------------------
if [[ ! -e "${FILE_PATH}" && ! -L "${FILE_PATH}" ]]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Whitelist: bypass when matched in .claude/axiarch-overwrite-allow.txt or .codex/...
# -----------------------------------------------------------------------------
ALLOW_AGENT="claude"
if [[ "${AXIARCH_HOOK_AGENT:-}" == "codex" ]]; then
  ALLOW_AGENT="codex"
elif [[ -e "${PROJECT_DIR}/.claude/settings.json" || -L "${PROJECT_DIR}/.claude/settings.json" ||
        -e "${PROJECT_DIR}/.claude/axiarch-overwrite-allow.txt" || -L "${PROJECT_DIR}/.claude/axiarch-overwrite-allow.txt" ]]; then
  ALLOW_AGENT="claude"
elif [[ -e "${PROJECT_DIR}/.codex/axiarch-overwrite-allow.txt" || -L "${PROJECT_DIR}/.codex/axiarch-overwrite-allow.txt" ]]; then
  # Legacy standalone Write guards without an installed Claude configuration.
  ALLOW_AGENT="codex"
fi

# Validate the entire file before matching; process substitution would lose the
# reader's failure status. Keep Bash glob semantics for legacy Write callers.
ALLOW_PATTERNS="$(python3 "$HOOK_HELPER" allow-patterns --project "$PROJECT_DIR" --agent "$ALLOW_AGENT")" || exit 2
if [[ -n "${ALLOW_PATTERNS}" ]]; then
  MATCH_PATH="$(decode_field canonical)" || exit 2
  MATCH_PATH="${MATCH_PATH%.}"
  while IFS= read -r pattern || [[ -n "${pattern}" ]]; do
    # Relative allow patterns are explicitly relative to this project.
    [[ "$pattern" == /* ]] || pattern="$PROJECT_DIR/$pattern"
    # Glob match (case-sensitive)
    # shellcheck disable=SC2053
    if [[ "${MATCH_PATH}" == ${pattern} ]]; then
      exit 0
    fi
  done <<< "${ALLOW_PATTERNS}"
fi

# -----------------------------------------------------------------------------
# Deny: existing file + Write tool = potential §7.6 ANTI-FULL-OVERWRITE violation
# -----------------------------------------------------------------------------
REASON_JA="AXIARCH.md Anti-Full-Overwrite: 既存ファイル '${FILE_PATH}' を Write tool で全面書き換えしようとしています。差分編集には Edit tool を使用してください。意図的な全面置換には記録されたユーザー明示承認が必要です。既存の承認範囲を確認し、不足する場合だけ承認を求め、.claude/axiarch-overwrite-allow.txt または .codex/axiarch-overwrite-allow.txt に承認済みパスを追加してください。"
REASON_EN="AXIARCH.md Anti-Full-Overwrite: file '${FILE_PATH}' already exists; the AI must use Edit (diff-based) instead of Write (full overwrite). Intentional full replacement requires recorded explicit user approval. Check the existing authorization scope, ask only when approval is missing, and add the approved path to .claude/axiarch-overwrite-allow.txt or .codex/axiarch-overwrite-allow.txt."

# Emit JSON output for hook contract (decision: block + reason)
REASON_FULL="${REASON_JA} / ${REASON_EN}"
printf '%s' "$REASON_FULL" | python3 -c 'import json, sys; print(json.dumps({"decision": "block", "reason": sys.stdin.read()}))'

# Also write a human-readable message to stderr for transcripts that may not
# render the JSON decision payload.
printf '\n[axiarch:protect-antifull] BLOCKED — %s\n' "${REASON_FULL}" >&2

# Exit code 2 — Claude Code treats this as a hard block on the tool call.
exit 2
